spring:
  application:
    name: rsupport-test
  config:
    activate:
      on-profile: local
  h2:
    console: true
    path: /h2-console
server:
  port: 8080

projects:
  rsupport:
    hibernate:
      property:
        "[hibernate.show_sql]": false
        "[hibernate.cache.use_second_level_cache]": false
        "[hibernate.cache.use_query_cache]": false
    datasource:
      jdbc-url: 'jdbc:h2:mem:rsupport'
      driver-class-name: org.h2.Driver
      url: jdbc:h2:rsupport/test
      username: admin
      password: 1234!
      hikari:
        connection-timeout: 50000


decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org:
      springframework:
        security: debug
    rsupport: debug

